sudo: required
services:
  - docker
before_install:
  - sudo apt-get install jq
  - docker pull multiarch/qemu-user-static
env:
  - ADDON="caddy_proxy"
script:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - ./build.sh $ADDON 
